server:
  error:
    include-stacktrace: never

springdoc:
  swagger-ui:
    path: /swagger-ui.html

spring:
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false

  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}

  jpa:
    show-sql: false

logging:
  level:
    ROOT: INFO
